import config from "./config.js";
import SnakeGameState from "./snake_game_state.js";

class SnakeManager{
    // Instance of snake game state class.
    static game;
    // Memorize whether game is currently running to avoid errors generated by pressing buttons many times.
    static isRunning = false;
    // Value of setTimeout(). used to adjust game speed
    static speedValue = 100;
    // variable used to save return value of setInterval() to be able to clear it.
    static saveFunc;

    /**
     * Initialize game and controls on page
     */
    constructor(){
        // Make sure we have max_score key:value initialized in localstorage
        if(['', null].includes(localStorage.getItem(config.maxScoreKey)))
            localStorage.setItem(config.maxScoreKey, '0');
        // Initialize game
        SnakeManager.game = new SnakeGameState(config.numRows, config.numColumns, config.rectSize, config.snakeState, document.getElementById(config.screenElemID));
        // Initialize controls
        SnakeManager._addSpeedControl();
        SnakeManager._addGameControls();
        SnakeManager._addKeyListeners();
    }

    /**
     * Displays message that contains current game score and record score.
     * 
     * @param {number} score Score of finished game.
     */
    static displayResult(score){
        let displayText = 'You died!\nYour score: ' + score + '\nRecord score: ' + SnakeGameState.getMaxScore(); 
        alert(displayText);
    }

    /**
     * Advance game state by one step.
     * Resets game state if game is finished and desplays the result of the last game.
     */
    static playOnce(){
        let result = SnakeManager.game.playOneStep();
        if(result != -1){ // Check if game is finished.
            SnakeManager.isRunning = false;
            SnakeManager.reset();
            SnakeManager.displayResult(result);
        }
    }

    /**
     * Unpauses the game.
     */
    static startPlaying(){ // Set interval and start playing again
        if(!SnakeManager.isRunning){
            SnakeManager.isRunning = true;
            SnakeManager.saveFunc = setInterval(SnakeManager.playOnce, SnakeManager.speedValue);
        }
    }

    /**
     * Resets gamestate according to entered values taken from input.
     * If input is empty or invalid, initializes to default values.
     */
    static reset(){ // Stop playing game and get game state ready for the new SnakeManager.game
        SnakeManager.isRunning = false; // No need to check. Stop can be called even if game is paused or reset already.
        clearInterval(SnakeManager.saveFunc);
        SnakeManager.game.stopGame();
        let newRows = document.getElementById(config.rowInputID).value;
        let newCols = document.getElementById(config.colInputID).value;
        if(isNaN(newRows) || isNaN(newCols) || newRows < 10 || newCols < 10 || newRows > 40 || newCols > 100){
            newRows = config.numRows;
            newCols = config.numColumns;
        }
        const screen = document.getElementById(config.screenElemID);
        screen.style.height = (23 + config.rectSize * newRows) + 'px';
        screen.style.width = (23 + config.rectSize * newCols) + 'px';
    
        SnakeManager.game = new SnakeGameState(newRows, newCols, config.rectSize, config.snakeState, document.getElementById(config.screenElemID));
    }

    /**
     * Stops playing game, but doesn't change game state
     */
    static pauseGame(){
        if(SnakeManager.isRunning){
            SnakeManager.isRunning = false;
            clearInterval(SnakeManager.saveFunc);
        }
    }

    /**
     * Adds eventlistener to speed slider.
     */
    static _addSpeedControl(){
        const speedInput = document.getElementById(config.speedInputID);
        speedInput.addEventListener('click', function(){
            const newSpeed = document.getElementById(config.speedInputID).value;
            SnakeManager.speedValue = 150 - 10 * newSpeed;
            if(SnakeManager.isRunning){
                clearInterval(SnakeManager.saveFunc);
                SnakeManager.saveFunc = setInterval(SnakeManager.playOnce, SnakeManager.speedValue);
            }
        });
    }

    /**
     * Adds eventlisteners to game control buttons.
     */
    static _addGameControls(){
        const startButton = document.getElementById('start-button');
        startButton.addEventListener('click', function(){
            SnakeManager.startPlaying();
        });
        const resetButton = document.getElementById('reset-button');
        resetButton.addEventListener('click', function(){
            SnakeManager.reset();
        });
        const pauseButton = document.getElementById('pause-button');
        pauseButton.addEventListener('click', function(){
            SnakeManager.pauseGame();
        });
    }

    /**
     * Adds eventlisteners to control during game(Arrow keys) and
     * keys that represent game state control buttons.
     */
    static _addKeyListeners(){
        document.addEventListener('keydown', logKey);
        function logKey(e){
            const curKey = `${e.code}`;
            // If arrow key is pressed, change value of the next direction.
            if([config.dirTop, config.dirDown, config.dirLeft, config.dirRight].includes(curKey)){
                SnakeManager.game.updateDirection(curKey);
            } else { // Keys that represent game state control buttons.
                switch(curKey){
                    case 'KeyP':
                        SnakeManager.pauseGame();
                        break;
                    case 'KeyS':
                        SnakeManager.startPlaying();
                        break;
                    case 'KeyR':
                        SnakeManager.reset();
                        break;
                }
            }
        };
    }
}

const newGame = new SnakeManager();